### ISSUE TITLE
Code of paper "Reversible Vision Transformers"

### ISSUE THREAD

**Issue by iamhankai** [facebookresearch/mvit#10]
I do not find code about Reversible Vision Transformers. Will it be released?

**Comment by lyttonhao** [comment]
Yes, I will be released

**Comment by karttikeya** [comment]
Hi, 

Thanks for interested in the work. We have released the code (+model weights and recipes) in pyslowfast first : `https://github.com/facebookresearch/SlowFast/tree/main/projects/rev` and will soon also release in this codebase here.

**Comment by iamhankai** [comment]
Thanks for the notification.
