### ISSUE TITLE
spatial-temporal relative positional embedding?

### ISSUE THREAD

**Issue by JunweiLiang** [facebookresearch/mvit#4]
Any suggestions on how to implement spatial-temporal relative positional embeddings? I'm trying to extend based on the `cal_rel_pos_spatial` function in `attention.py`

Thanks,
Junwei

**Comment by lyttonhao** [comment]
Hi, you can follow `cal_rel_pos_spatial` to add a separate temporal rel pos embedding.
Our official spatial-temporal rel pos embedding will be released in [PySlowFast](https://github.com/facebookresearch/SlowFast) (our video codebase) soon together with the MViTv2 video models.
