### ISSUE TITLE
pre-training model

### ISSUE THREAD

**Issue by yan-ctrl** [facebookresearch/mvit#5]
Hello, thank you for your work. Is there a pre-training model of AVA dataset?

**Comment by lyttonhao** [comment]
It will be released in PySlowfast codebase for video models

**Comment by yan-ctrl** [comment]
Thank you, looking forward to the update.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebookresearch/mvit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月11日(星期六) 凌晨1:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebookresearch/mvit] pre-training model (Issue #5)





 
It will be released in PySlowfast codebase for video models

**Comment by vateye** [comment]
> 

Hi, when will the MViTv2 be available on PySlowFast? Since I find it hard to write the model by myself. Thanks in advance.

**Comment by vateye** [comment]
> It will be released in PySlowfast codebase for video models

Hi, when will MViTv2 be available on PySlowFast? Since I find it hard to implement by myself. Thanks in advance.
